name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm build
        run: |
          ls -1 | grep -v ^node_modules | grep -v ^README | awk -F '.md' '{print "[" $1 "](./" $1 ")\n" }' >> README.md
          mkdir -p ./.vuepress && echo "module.exports={base:'/hello-actions/'}"  > ./.vuepress/config.js
          yarn add vuepress
          npx vuepress build .
        env:
          CI: true

      - name: Deploy to GitHub Pages
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR : .vuepress/dist/
          GH_PAT: ${{ secrets.GH_PAT }}

